### PR TITLE
Add PSModule to the index.ts root

### LINKED ISSUE #10: pactsafe-angular-sdk giving compiler error when upgraded angular project from version 8 to 10.
Hi @JJWill0ughby @eprugh,

I have AngularCli generated project initally version is 8 there i am using  "pactsafe-angular-sdk": "^0.1.2", and all working fine.

Now currently i am upgrading angular version to 10 and facing issue while compilation as below 

[INFO] chunk {} runtime.acf0dec4155e77772545.js (runtime) 1.45 kB [entry] [rendered]
[INFO] ERROR in node_modules/pactsafe-angular-sdk/index.d.ts:5:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
[INFO] chunk {1} main.32a5bf83ddf75a6d3667.js (main) 128 bytes [initial] [rendered]
[INFO]
[INFO] chunk {2} polyfills.4b1f18e0602c4a1bab0a.js (polyfills) 130 bytes [initial] [rendered]
[INFO] 5     static forRoot(): ModuleWithProviders;
[INFO] chunk {3} polyfills-es5.b767e4712bb767052abe.js (polyfills-es5) 83 kB [initial] [rendered]

I also tried solution given in notes. i.e

If you are developing in an AngularCli generated project, you may run into trouble using the library. Make sure you set up a path mapping in /src/tsconfig.app.json of your consuming application (not the library) and that should solve any compilation problems you may have:

{
  "compilerOptions": {
    // ...
    // Note: these paths are relative to 'baseUrl' path.
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
  }
}
still facing issue.
I am not much clear on what all paths need to mention here . cloud you please provide some inputs .

Compiler option in my projects

 "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": [],
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"    
      ]
    }
  }

### PR DESCRIPTION
**Pull request by mewelling**
fixes #10

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -56,13 +62,18 @@
...
-    "zone.js": "^0.8.4"
+    "typescript": "~3.8.3",
+    "zone.js": "~0.10.3"
   },
   "engines": {
     "node": ">=6.0.0"
+  },
+  "dependencies": {
+    "@angular/cli": "^9.1.15",
+    "rxjs-compat": "^6.0.0-rc.0",
```
Comment (mewelling) [inline package.json:76]: is there a working stable version that isn't a release candidate?

Comment (brdly-smith) [reply package.json]: tested 6.6.7 appears to be working
